# Site settings

author: Robert San
email: robertsanseries@gmail.com
twitter_username: robertsanseries
github_username:  robertsanseries
googleplus_username: robertsanseries

url_vanat_github: https://github.com/vanat/vanat
url_vanat_gitter: https://gitter.im/vanat/vanat

head-title: Vanat - Dependency Manager for Vala
title: Vanat

baseurl: "https://vanat.github.io"
#baseurl: "/vanat"    # the subpath of your site, "/blog"
url: ""

# footer 
description: "Vanat will allow us to speed up the development with Vala. I`m excited to see that happen. ~ Robert San"

favo: ""
descrpt: ""


#
# Build settings
#

#exclude: [vendor]

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  highlight: true
  auto_ids:  true

sass:
  style: compressed

permalink: /posts/:categories/:title.html

paginate: 7
#paginate_path: 'page/:num'

gems: [jekyll-paginate, jekyll-last-modified-at, jemoji]


#
# Custom
#

# Color
# All css class, see: http://materializecss.com/color.html
header-color: "white"
head-theme-color: ""     # MUST in hex format, may the same as header-color. This color is for android chrome browser.

footer-color: "deep-orange lighten-4"
footer-color-below: ""
#footer-button-color: "indigo lighten-2"
#footer-link-color: "red-text text-accent-1"

share-button-color: "deep-orange lighten-4"
#share-button-small-color: ""


##
#excerpt_separator: <!-- excerpt_end -->       # for post.excerpt

